In [3]:
from pathlib import Path

import pandas as pd

In [4]:
DATA_DIR = Path("../data")
PROCESSED_DATA_PATH = DATA_DIR / "processed" / "sales_data_cleaned.csv"

pd.set_option("display.max_columns", None)
pd.set_option("display.float_format", "{:,.2f}".format)

In [5]:
sales_df = pd.read_csv(
    PROCESSED_DATA_PATH,
    parse_dates=["ORDERDATE"]
)

sales_df.head()

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,PRODUCTLINE,MSRP,PRODUCTCODE,CUSTOMERNAME,PHONE,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,"2,871.00",2003-02-24,Shipped,1,2,2003,Motorcycles,95,S10_1678,Land of Toys Inc.,NaN,897 Long Airport Avenue,NaN,NYC,NY,NaN,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,"2,765.90",2003-05-07,Shipped,2,5,2003,Motorcycles,95,S10_1678,Reims Collectables,26.47.1555,59 rue de l'Abbaye,NaN,Reims,NaN,NaN,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,"3,884.34",2003-07-01,Shipped,3,7,2003,Motorcycles,95,S10_1678,Lyon Souveniers,+33 1 46 62 7555,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,NaN,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,"3,746.70",2003-08-25,Shipped,3,8,2003,Motorcycles,95,S10_1678,Toys4GrownUps.com,NaN,78934 Hillside Dr.,NaN,Pasadena,CA,NaN,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,"5,205.27",2003-10-10,Shipped,4,10,2003,Motorcycles,95,S10_1678,Corporate Gift Ideas Co.,NaN,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium

In [4]:
# Business Question 1
# Bagaimana total penjualan setiap tahun?

yearly_sales = (
    sales_df
    .groupby("YEAR_ID", as_index=False)
    .agg(
        Total_Sales=("SALES", "sum")
    )
    .sort_values("YEAR_ID")
)

yearly_sales

best_year = yearly_sales.loc[
    yearly_sales["Total_Sales"].idxmax()
]

best_year

YEAR_ID           2,004.00
Total_Sales   4,724,162.60
Name: 1, dtype: float64

In [5]:
# Business Question 2
# Negara dengan penjualan Classic Cars terbesar pada tahun 2004

classic_2004 = sales_df[
    (sales_df["YEAR_ID"] == 2004) &
    (sales_df["PRODUCTLINE"] == "Classic Cars")
]

country_sales = (
    classic_2004
    .groupby("COUNTRY", as_index=False)
    .agg(
        Total_Sales=("SALES", "sum")
    )
    .sort_values(
        by="Total_Sales",
        ascending=False
    )
)

country_sales

top_country = country_sales.iloc[0]

top_country

COUNTRY              USA
Total_Sales   560,448.26
Name: 18, dtype: object

In [6]:
# Business Question 3
# Product Line dengan Quantity Ordered terbesar pada periode September 2003 hingga Maret 2004
filtered_df = sales_df[
    (sales_df["ORDERDATE"] >= "2003-09-01") &
    (sales_df["ORDERDATE"] <= "2004-03-31")
]

product_quantity = (
    filtered_df
    .groupby("PRODUCTLINE", as_index=False)
    .agg(
        Total_Quantity=("QUANTITYORDERED", "sum")
    )
    .sort_values(
        by="Total_Quantity",
        ascending=False
    )
)

product_quantity

top_product = product_quantity.iloc[0]

top_product

PRODUCTLINE       Classic Cars
Total_Quantity           11083
Name: 0, dtype: object

In [7]:
# Executive Summary
# Business Question 1
best_year = (
    sales_df.groupby("YEAR_ID", as_index=False)
    .agg(Total_Sales=("SALES", "sum"))
    .sort_values("Total_Sales", ascending=False)
    .iloc[0]
)

# Business Question 2
top_country = (
    sales_df[
        (sales_df["YEAR_ID"] == 2004) &
        (sales_df["PRODUCTLINE"] == "Classic Cars")
    ]
    .groupby("COUNTRY", as_index=False)
    .agg(Total_Sales=("SALES", "sum"))
    .sort_values("Total_Sales", ascending=False)
    .iloc[0]
)

# Business Question 3
top_product = (
    sales_df[
        (sales_df["ORDERDATE"] >= "2003-09-01") &
        (sales_df["ORDERDATE"] <= "2004-03-31")
    ]
    .groupby("PRODUCTLINE", as_index=False)
    .agg(Total_Quantity=("QUANTITYORDERED", "sum"))
    .sort_values("Total_Quantity", ascending=False)
    .iloc[0]
)

summary = pd.DataFrame({
    "Business Question": [
        "Highest Sales Year",
        "Top Country (Classic Cars - 2004)",
        "Top Product Line (Sep 2003 - Mar 2004)"
    ],
    "Key Result": [
        best_year["YEAR_ID"],
        top_country["COUNTRY"],
        top_product["PRODUCTLINE"]
    ],
    "Metric": [
        f"${best_year['Total_Sales']:,.2f}",
        f"${top_country['Total_Sales']:,.2f}",
        f"{top_product['Total_Quantity']:,} Units"
    ]
})

summary

                        Business Question    Key Result         Metric
0                      Highest Sales Year      2,004.00  $4,724,162.60
1       Top Country (Classic Cars - 2004)           USA    $560,448.26
2  Top Product Line (Sep 2003 - Mar 2004)  Classic Cars   11,083 Units